//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio.Test.Droid.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Basket {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Basket() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio.Test.Droid.LocalizationResx.Basket", typeof(Basket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Basket_Title {
            get {
                return ResourceManager.GetString("Basket_Title", resourceCulture);
            }
        }
        
        internal static string Basket_DeleteItem {
            get {
                return ResourceManager.GetString("Basket_DeleteItem", resourceCulture);
            }
        }
        
        internal static string Basket_OrderBy {
            get {
                return ResourceManager.GetString("Basket_OrderBy", resourceCulture);
            }
        }
        
        internal static string Basket_EmptyTitle {
            get {
                return ResourceManager.GetString("Basket_EmptyTitle", resourceCulture);
            }
        }
        
        internal static string Basket_EmptyText {
            get {
                return ResourceManager.GetString("Basket_EmptyText", resourceCulture);
            }
        }
        
        internal static string Basket_EmptyButton {
            get {
                return ResourceManager.GetString("Basket_EmptyButton", resourceCulture);
            }
        }
        
        internal static string Basket_AddedToBasketTitle {
            get {
                return ResourceManager.GetString("Basket_AddedToBasketTitle", resourceCulture);
            }
        }
        
        internal static string Basket_AddedToBasketButton {
            get {
                return ResourceManager.GetString("Basket_AddedToBasketButton", resourceCulture);
            }
        }
        
        internal static string Basket_ProductsCount {
            get {
                return ResourceManager.GetString("Basket_ProductsCount", resourceCulture);
            }
        }
        
        internal static string Basket_Delete {
            get {
                return ResourceManager.GetString("Basket_Delete", resourceCulture);
            }
        }
        
        internal static string Basket_DeleteYes {
            get {
                return ResourceManager.GetString("Basket_DeleteYes", resourceCulture);
            }
        }
        
        internal static string Order_Title {
            get {
                return ResourceManager.GetString("Order_Title", resourceCulture);
            }
        }
        
        internal static string Order_Postcard {
            get {
                return ResourceManager.GetString("Order_Postcard", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryTypeHeader {
            get {
                return ResourceManager.GetString("Order_DeliveryTypeHeader", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryPrice {
            get {
                return ResourceManager.GetString("Order_DeliveryPrice", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryPriceAlert {
            get {
                return ResourceManager.GetString("Order_DeliveryPriceAlert", resourceCulture);
            }
        }
        
        internal static string Order_OrderBy {
            get {
                return ResourceManager.GetString("Order_OrderBy", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryTimeAndDay {
            get {
                return ResourceManager.GetString("Order_DeliveryTimeAndDay", resourceCulture);
            }
        }
        
        internal static string Order_Done {
            get {
                return ResourceManager.GetString("Order_Done", resourceCulture);
            }
        }
        
        internal static string Order_Free {
            get {
                return ResourceManager.GetString("Order_Free", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryEmptyText {
            get {
                return ResourceManager.GetString("Order_DeliveryEmptyText", resourceCulture);
            }
        }
        
        internal static string Order_DeliveryPriceFrom {
            get {
                return ResourceManager.GetString("Order_DeliveryPriceFrom", resourceCulture);
            }
        }
        
        internal static string Order_TimeDone {
            get {
                return ResourceManager.GetString("Order_TimeDone", resourceCulture);
            }
        }
        
        internal static string Order_TimeCancel {
            get {
                return ResourceManager.GetString("Order_TimeCancel", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_Title {
            get {
                return ResourceManager.GetString("DeliveryPoint_Title", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_Confirm {
            get {
                return ResourceManager.GetString("DeliveryPoint_Confirm", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_Details {
            get {
                return ResourceManager.GetString("DeliveryPoint_Details", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_MakeCallText {
            get {
                return ResourceManager.GetString("DeliveryPoint_MakeCallText", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_MakeCall {
            get {
                return ResourceManager.GetString("DeliveryPoint_MakeCall", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_CallError {
            get {
                return ResourceManager.GetString("DeliveryPoint_CallError", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_RouteError {
            get {
                return ResourceManager.GetString("DeliveryPoint_RouteError", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_OnMap {
            get {
                return ResourceManager.GetString("DeliveryPoint_OnMap", resourceCulture);
            }
        }
        
        internal static string DeliveryPoint_SearchHint {
            get {
                return ResourceManager.GetString("DeliveryPoint_SearchHint", resourceCulture);
            }
        }
        
        internal static string DeliveryAddress_Title {
            get {
                return ResourceManager.GetString("DeliveryAddress_Title", resourceCulture);
            }
        }
        
        internal static string DeliveryAddress_DeliveryPrice {
            get {
                return ResourceManager.GetString("DeliveryAddress_DeliveryPrice", resourceCulture);
            }
        }
        
        internal static string DeliveryAddress_DeliveryFree {
            get {
                return ResourceManager.GetString("DeliveryAddress_DeliveryFree", resourceCulture);
            }
        }
        
        internal static string DeliveryAddress_Confirm {
            get {
                return ResourceManager.GetString("DeliveryAddress_Confirm", resourceCulture);
            }
        }
        
        internal static string Payment_Title {
            get {
                return ResourceManager.GetString("Payment_Title", resourceCulture);
            }
        }
        
        internal static string Thanks_Title {
            get {
                return ResourceManager.GetString("Thanks_Title", resourceCulture);
            }
        }
        
        internal static string Thanks_Text {
            get {
                return ResourceManager.GetString("Thanks_Text", resourceCulture);
            }
        }
        
        internal static string Thanks_Catalog {
            get {
                return ResourceManager.GetString("Thanks_Catalog", resourceCulture);
            }
        }
        
        internal static string BasketProductCard_AddToBasket {
            get {
                return ResourceManager.GetString("BasketProductCard_AddToBasket", resourceCulture);
            }
        }
        
        internal static string BasketProductCard_Done {
            get {
                return ResourceManager.GetString("BasketProductCard_Done", resourceCulture);
            }
        }
        

        internal static string BasketCatalogCard_AddToBasket {
            get {
                return ResourceManager.GetString("BasketCatalogCard_AddToBasket", resourceCulture);
            }
        }

        internal static string Error_Delivery_Text {
            get {
                return ResourceManager.GetString("Error_Delivery_Text", resourceCulture);
            }
        }
        
        internal static string Error_Delivery_Time_Text {
            get {
                return ResourceManager.GetString("Error_Delivery_Time_Text", resourceCulture);
            }
        }
    }
}
