//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio.Test.Droid.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HistoryOrders_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistoryOrders_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio.Test.Droid.LocalizationResx.HistoryOrders.ru", typeof(HistoryOrders_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        internal static string History_OrderList {
            get {
                return ResourceManager.GetString("History_OrderList", resourceCulture);
            }
        }
        
        internal static string Status_Paid {
            get {
                return ResourceManager.GetString("Status_Paid", resourceCulture);
            }
        }
        
        internal static string Status_NotPaid {
            get {
                return ResourceManager.GetString("Status_NotPaid", resourceCulture);
            }
        }
        
        internal static string HistoryOrderProducts_Title {
            get {
                return ResourceManager.GetString("HistoryOrderProducts_Title", resourceCulture);
            }
        }
        
        internal static string HistoryOrderProducts_Pieces {
            get {
                return ResourceManager.GetString("HistoryOrderProducts_Pieces", resourceCulture);
            }
        }
        
        internal static string HistoryOrderProducts_OutOfStock {
            get {
                return ResourceManager.GetString("HistoryOrderProducts_OutOfStock", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_ToBasket {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_ToBasket", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_Title {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_Title", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_OrderList {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_OrderList", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_Delivery {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_Delivery", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_PaymentType {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_PaymentType", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_Amount {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_Amount", resourceCulture);
            }
        }
        
        internal static string HistoryOrderDetails_RepeatOrder {
            get {
                return ResourceManager.GetString("HistoryOrderDetails_RepeatOrder", resourceCulture);
            }
        }
    }
}
