//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Auth_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auth_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Auth.ru", typeof(Auth_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TermsText {
            get {
                return ResourceManager.GetString("TermsText", resourceCulture);
            }
        }
        
        internal static string email1_placeholder {
            get {
                return ResourceManager.GetString("email1_placeholder", resourceCulture);
            }
        }
        
        internal static string textField2_placeholder {
            get {
                return ResourceManager.GetString("textField2_placeholder", resourceCulture);
            }
        }
        
        internal static string textField21_placeholder {
            get {
                return ResourceManager.GetString("textField21_placeholder", resourceCulture);
            }
        }
        
        internal static string picker3_placeholder {
            get {
                return ResourceManager.GetString("picker3_placeholder", resourceCulture);
            }
        }
        
        internal static string picker3_values {
            get {
                return ResourceManager.GetString("picker3_values", resourceCulture);
            }
        }
        
        internal static string picker4_placeholder {
            get {
                return ResourceManager.GetString("picker4_placeholder", resourceCulture);
            }
        }
        
        internal static string picker4_values {
            get {
                return ResourceManager.GetString("picker4_values", resourceCulture);
            }
        }
        
        internal static string date5_placeholder {
            get {
                return ResourceManager.GetString("date5_placeholder", resourceCulture);
            }
        }
        
        internal static string password6_placeholder {
            get {
                return ResourceManager.GetString("password6_placeholder", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string SocialAuthCancel {
            get {
                return ResourceManager.GetString("SocialAuthCancel", resourceCulture);
            }
        }
        
        internal static string SocialAuthError {
            get {
                return ResourceManager.GetString("SocialAuthError", resourceCulture);
            }
        }
        
        internal static string Auth_SignIn {
            get {
                return ResourceManager.GetString("Auth_SignIn", resourceCulture);
            }
        }
        
        internal static string Auth_SignUp {
            get {
                return ResourceManager.GetString("Auth_SignUp", resourceCulture);
            }
        }
        
        internal static string Auth_Skip {
            get {
                return ResourceManager.GetString("Auth_Skip", resourceCulture);
            }
        }
        
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
        
        internal static string SignUp_Join {
            get {
                return ResourceManager.GetString("SignUp_Join", resourceCulture);
            }
        }
        
        internal static string SignUp_Next {
            get {
                return ResourceManager.GetString("SignUp_Next", resourceCulture);
            }
        }
        
        internal static string Thanks_Thanks {
            get {
                return ResourceManager.GetString("Thanks_Thanks", resourceCulture);
            }
        }
        
        internal static string Thanks_Motivation {
            get {
                return ResourceManager.GetString("Thanks_Motivation", resourceCulture);
            }
        }
        
        internal static string Thanks_Start {
            get {
                return ResourceManager.GetString("Thanks_Start", resourceCulture);
            }
        }
        
        internal static string SignIn_Title {
            get {
                return ResourceManager.GetString("SignIn_Title", resourceCulture);
            }
        }
        
        internal static string SignIn_Join {
            get {
                return ResourceManager.GetString("SignIn_Join", resourceCulture);
            }
        }
        
        internal static string SignIn_PhonePlaceholder {
            get {
                return ResourceManager.GetString("SignIn_PhonePlaceholder", resourceCulture);
            }
        }
        
        internal static string SignIn_EmailPlaceholder {
            get {
                return ResourceManager.GetString("SignIn_EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string SignIn_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("SignIn_PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string SignIn_SignIn {
            get {
                return ResourceManager.GetString("SignIn_SignIn", resourceCulture);
            }
        }
        
        internal static string SignIn_RestorePassword {
            get {
                return ResourceManager.GetString("SignIn_RestorePassword", resourceCulture);
            }
        }
        
        internal static string SignIn_Motivation {
            get {
                return ResourceManager.GetString("SignIn_Motivation", resourceCulture);
            }
        }
        
        internal static string Password_Reset_Title {
            get {
                return ResourceManager.GetString("Password_Reset_Title", resourceCulture);
            }
        }
        
        internal static string Password_Reset_PhonePlaceholder {
            get {
                return ResourceManager.GetString("Password_Reset_PhonePlaceholder", resourceCulture);
            }
        }
        
        internal static string Password_Reset_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Password_Reset_EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string Password_Reset_Forgot {
            get {
                return ResourceManager.GetString("Password_Reset_Forgot", resourceCulture);
            }
        }
        
        internal static string Password_Reset_MotivationPhone {
            get {
                return ResourceManager.GetString("Password_Reset_MotivationPhone", resourceCulture);
            }
        }
        
        internal static string Password_Reset_MotivationEmail {
            get {
                return ResourceManager.GetString("Password_Reset_MotivationEmail", resourceCulture);
            }
        }
        
        internal static string Password_Reset_GetCode {
            get {
                return ResourceManager.GetString("Password_Reset_GetCode", resourceCulture);
            }
        }
        
        internal static string Password_Reset_GetPassword {
            get {
                return ResourceManager.GetString("Password_Reset_GetPassword", resourceCulture);
            }
        }
        
        internal static string Password_Reset_Close {
            get {
                return ResourceManager.GetString("Password_Reset_Close", resourceCulture);
            }
        }
        
        internal static string Password_Reset_EmailInstruction {
            get {
                return ResourceManager.GetString("Password_Reset_EmailInstruction", resourceCulture);
            }
        }
        
        internal static string Password_Reset_PasswordSent {
            get {
                return ResourceManager.GetString("Password_Reset_PasswordSent", resourceCulture);
            }
        }
        
        internal static string Password_Sms_Title {
            get {
                return ResourceManager.GetString("Password_Sms_Title", resourceCulture);
            }
        }
        
        internal static string Password_Sms_SentAgain {
            get {
                return ResourceManager.GetString("Password_Sms_SentAgain", resourceCulture);
            }
        }
        
        internal static string Password_Sms_ConfirmCode {
            get {
                return ResourceManager.GetString("Password_Sms_ConfirmCode", resourceCulture);
            }
        }
        
        internal static string Password_Sms_CodePlaceholder {
            get {
                return ResourceManager.GetString("Password_Sms_CodePlaceholder", resourceCulture);
            }
        }
        
        internal static string Password_Sms_CodeText {
            get {
                return ResourceManager.GetString("Password_Sms_CodeText", resourceCulture);
            }
        }
        
        internal static string Password_Sms_CodeFromSms {
            get {
                return ResourceManager.GetString("Password_Sms_CodeFromSms", resourceCulture);
            }
        }
        
        internal static string Password_Sms_SentToPhone {
            get {
                return ResourceManager.GetString("Password_Sms_SentToPhone", resourceCulture);
            }
        }
        
        internal static string Password_New_Title {
            get {
                return ResourceManager.GetString("Password_New_Title", resourceCulture);
            }
        }
        
        internal static string Password_New_ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("Password_New_ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string Password_New_NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("Password_New_NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string Password_New_NewPassword {
            get {
                return ResourceManager.GetString("Password_New_NewPassword", resourceCulture);
            }
        }
        
        internal static string Password_New_Motivation {
            get {
                return ResourceManager.GetString("Password_New_Motivation", resourceCulture);
            }
        }
        
        internal static string Password_New_Done {
            get {
                return ResourceManager.GetString("Password_New_Done", resourceCulture);
            }
        }
    }
}
