//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Best2Pay_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Best2Pay_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Best2Pay.ru", typeof(Best2Pay_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Purchase_Failed {
            get {
                return ResourceManager.GetString("Purchase_Failed", resourceCulture);
            }
        }
        
        internal static string Payment_OrderNumber {
            get {
                return ResourceManager.GetString("Payment_OrderNumber", resourceCulture);
            }
        }
        
        internal static string Operation_ErrorDefault {
            get {
                return ResourceManager.GetString("Operation_ErrorDefault", resourceCulture);
            }
        }
        
        internal static string Operation_Error0 {
            get {
                return ResourceManager.GetString("Operation_Error0", resourceCulture);
            }
        }
        
        internal static string Operation_Error3 {
            get {
                return ResourceManager.GetString("Operation_Error3", resourceCulture);
            }
        }
        
        internal static string Operation_Error5 {
            get {
                return ResourceManager.GetString("Operation_Error5", resourceCulture);
            }
        }
        
        internal static string Operation_Error12 {
            get {
                return ResourceManager.GetString("Operation_Error12", resourceCulture);
            }
        }
        
        internal static string Operation_Error16 {
            get {
                return ResourceManager.GetString("Operation_Error16", resourceCulture);
            }
        }
    }
}
