//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Feedback_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Feedback_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Feedback.ru", typeof(Feedback_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MyReviews_Title {
            get {
                return ResourceManager.GetString("MyReviews_Title", resourceCulture);
            }
        }
        
        internal static string ReviewDetails_Title {
            get {
                return ResourceManager.GetString("ReviewDetails_Title", resourceCulture);
            }
        }
        
        internal static string ReviewDetails_Edit {
            get {
                return ResourceManager.GetString("ReviewDetails_Edit", resourceCulture);
            }
        }
        
        internal static string ReviewDetails_Delete {
            get {
                return ResourceManager.GetString("ReviewDetails_Delete", resourceCulture);
            }
        }
        
        internal static string ReviewDetails_Removed {
            get {
                return ResourceManager.GetString("ReviewDetails_Removed", resourceCulture);
            }
        }
        
        internal static string ReviewDetails_FailedToRemove {
            get {
                return ResourceManager.GetString("ReviewDetails_FailedToRemove", resourceCulture);
            }
        }
        
        internal static string ReviewPost_Sent {
            get {
                return ResourceManager.GetString("ReviewPost_Sent", resourceCulture);
            }
        }
        
        internal static string ReviewPost_FailedToSend {
            get {
                return ResourceManager.GetString("ReviewPost_FailedToSend", resourceCulture);
            }
        }
        
        internal static string Reviews_Title {
            get {
                return ResourceManager.GetString("Reviews_Title", resourceCulture);
            }
        }
        
        internal static string Reviews_New {
            get {
                return ResourceManager.GetString("Reviews_New", resourceCulture);
            }
        }
        
        internal static string Review_Title {
            get {
                return ResourceManager.GetString("Review_Title", resourceCulture);
            }
        }
        
        internal static string Review_Done {
            get {
                return ResourceManager.GetString("Review_Done", resourceCulture);
            }
        }
        
        internal static string Review_Send {
            get {
                return ResourceManager.GetString("Review_Send", resourceCulture);
            }
        }
    }
}
