//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Filters {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Filters() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Filters", typeof(Filters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Filters_Title {
            get {
                return ResourceManager.GetString("Filters_Title", resourceCulture);
            }
        }
        
        internal static string Filters_Apply {
            get {
                return ResourceManager.GetString("Filters_Apply", resourceCulture);
            }
        }
        
        internal static string Filters_Clear {
            get {
                return ResourceManager.GetString("Filters_Clear", resourceCulture);
            }
        }
        
        internal static string Sort_Title {
            get {
                return ResourceManager.GetString("Sort_Title", resourceCulture);
            }
        }
        
        internal static string Selection_Clear {
            get {
                return ResourceManager.GetString("Selection_Clear", resourceCulture);
            }
        }
        
        internal static string Selection_Apply {
            get {
                return ResourceManager.GetString("Selection_Apply", resourceCulture);
            }
        }
    }
}
