//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppRopio_ECommerce_Basket_Core_ViewModels_IBasketViewModel {
            get {
                return ResourceManager.GetString("AppRopio.ECommerce.Basket.Core.ViewModels.IBasketViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_ECommerce_Products_Core_ViewModels_IProductsViewModel {
            get {
                return ResourceManager.GetString("AppRopio.ECommerce.Products.Core.ViewModels.IProductsViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_ECommerce_HistoryOrders_Core_ViewModels_HistoryOrders_IHistoryOrdersViewModel {
            get {
                return ResourceManager.GetString("AppRopio.ECommerce.HistoryOrders.Core.ViewModels.HistoryOrders.IHistoryOrdersView" +
                        "Model", resourceCulture);
            }
        }
        
        internal static string AppRopio_ECommerce_Marked_Core_ViewModels_Marked_IMarkedViewModel {
            get {
                return ResourceManager.GetString("AppRopio.ECommerce.Marked.Core.ViewModels.Marked.IMarkedViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_Base_Contacts_Core_ViewModels_Contacts_IContactsViewModel {
            get {
                return ResourceManager.GetString("AppRopio.Base.Contacts.Core.ViewModels.Contacts.IContactsViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_Base_Map_Core_ViewModels_Points_List_IPointsListViewModel {
            get {
                return ResourceManager.GetString("AppRopio.Base.Map.Core.ViewModels.Points.List.IPointsListViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_Base_Information_Core_ViewModels_Information_IInformationViewModel {
            get {
                return ResourceManager.GetString("AppRopio.Base.Information.Core.ViewModels.Information.IInformationViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_Base_Settings_Core_ViewModels_Settings_ISettingsViewModel {
            get {
                return ResourceManager.GetString("AppRopio.Base.Settings.Core.ViewModels.Settings.ISettingsViewModel", resourceCulture);
            }
        }
        
        internal static string AppRopio_Feedback_Core_ViewModels_MyReviews_IMyReviewsViewModel {
            get {
                return ResourceManager.GetString("AppRopio.Feedback.Core.ViewModels.MyReviews.IMyReviewsViewModel", resourceCulture);
            }
        }
    }
}
