//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppRopio_Test.LocalizationResx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Products {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Products() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AppRopio_Test.LocalizationResx.Products", typeof(Products).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CategoriesEmptyTitle {
            get {
                return ResourceManager.GetString("CategoriesEmptyTitle", resourceCulture);
            }
        }
        
        internal static string OneProduct {
            get {
                return ResourceManager.GetString("OneProduct", resourceCulture);
            }
        }
        
        internal static string TwoProducts {
            get {
                return ResourceManager.GetString("TwoProducts", resourceCulture);
            }
        }
        
        internal static string FiveProducts {
            get {
                return ResourceManager.GetString("FiveProducts", resourceCulture);
            }
        }
        
        internal static string OutOfStock {
            get {
                return ResourceManager.GetString("OutOfStock", resourceCulture);
            }
        }
        
        internal static string ContentSearch_Title {
            get {
                return ResourceManager.GetString("ContentSearch_Title", resourceCulture);
            }
        }
        
        internal static string ContentSearch_ClearHistory {
            get {
                return ResourceManager.GetString("ContentSearch_ClearHistory", resourceCulture);
            }
        }
        
        internal static string ContentSearch_NoResultsTitle {
            get {
                return ResourceManager.GetString("ContentSearch_NoResultsTitle", resourceCulture);
            }
        }
        
        internal static string ContentSearch_NoResultsText {
            get {
                return ResourceManager.GetString("ContentSearch_NoResultsText", resourceCulture);
            }
        }
        
        internal static string ContentSearch_NoResultsCatalog {
            get {
                return ResourceManager.GetString("ContentSearch_NoResultsCatalog", resourceCulture);
            }
        }
        
        internal static string Catalog_Filters {
            get {
                return ResourceManager.GetString("Catalog_Filters", resourceCulture);
            }
        }
        
        internal static string Catalog_Sort {
            get {
                return ResourceManager.GetString("Catalog_Sort", resourceCulture);
            }
        }
        
        internal static string Selection_Clear {
            get {
                return ResourceManager.GetString("Selection_Clear", resourceCulture);
            }
        }
        
        internal static string Selection_Apply {
            get {
                return ResourceManager.GetString("Selection_Apply", resourceCulture);
            }
        }
    }
}
