#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppRopio.Geofencing.Droid.Resource", IsApplication=false)]

namespace AppRopio.Geofencing.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int push_icon = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int push_icon_silhouette = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f020000
			public static int push_color = 2130837504;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030002
			public static int geofence_not_available = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int geofence_too_many_geofences = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int geofence_too_many_pending_intents = 2130903044;
			
			// aapt resource value: 0x7f030009
			public static int geofence_transition_dwelled = 2130903049;
			
			// aapt resource value: 0x7f030007
			public static int geofence_transition_entered = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int geofence_transition_exited = 2130903048;
			
			// aapt resource value: 0x7f030006
			public static int geofence_transition_invalid_type = 2130903046;
			
			// aapt resource value: 0x7f03000b
			public static int geofence_transition_notification_text = 2130903051;
			
			// aapt resource value: 0x7f030000
			public static int library_name = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int not_connected = 2130903041;
			
			// aapt resource value: 0x7f030005
			public static int unknown_geofence_error = 2130903045;
			
			// aapt resource value: 0x7f03000a
			public static int unknown_geofence_transition = 2130903050;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
