#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppRopio.ECommerce.Loyalty.Droid.Resource", IsApplication=false)]

namespace AppRopio.ECommerce.Loyalty.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int MvxDropDownItemTemplate = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int MvxGroupItemTemplate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int MvxLang = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int MvxSource = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int MvxTemplate = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public static int app_loyalty_promocode_height = 2130837504;
			
			// aapt resource value: 0x7F020001
			public static int app_loyalty_promocode_inputLayout_horizontalMargin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public static int app_loyalty_promocode_inputLayout_verticalMargin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public static int app_loyalty_promocode_textinput_height = 2130837507;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public static int app_loyalty_promocode_editText = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int MvvmCrossTagId = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int MvxBindingTagUnique = 2130903042;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public static int app_loyalty_promocode = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public static int app_loyalty_promocode_inputLayout = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int app_loyalty_promocode_inputLayout_hintTextAppearance = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010004 }
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771972};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F010006 }
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010002 }
			public static int[] MvxExpandableListView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010005 }
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010003 }
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771971};
			
			// aapt resource value: 0
			public static int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public static int MvxListView_MvxItemTemplate = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
