#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppRopio.Base.Droid.Map.Resource", IsApplication=false)]

namespace AppRopio.Base.Droid.Map
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010007
			public static int ambientEnabled = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int buttonSize = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int cameraBearing = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int cameraMaxZoomPreference = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int cameraMinZoomPreference = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int cameraTargetLat = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int cameraTargetLng = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int cameraTilt = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int cameraZoom = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int circleCrop = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int colorScheme = 2130771985;
			
			// aapt resource value: 0x7F010012
			public static int font = 2130771986;
			
			// aapt resource value: 0x7F010013
			public static int fontProviderAuthority = 2130771987;
			
			// aapt resource value: 0x7F010014
			public static int fontProviderCerts = 2130771988;
			
			// aapt resource value: 0x7F010015
			public static int fontProviderFetchStrategy = 2130771989;
			
			// aapt resource value: 0x7F010016
			public static int fontProviderFetchTimeout = 2130771990;
			
			// aapt resource value: 0x7F010017
			public static int fontProviderPackage = 2130771991;
			
			// aapt resource value: 0x7F010018
			public static int fontProviderQuery = 2130771992;
			
			// aapt resource value: 0x7F010019
			public static int fontStyle = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public static int fontWeight = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public static int imageAspectRatio = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public static int imageAspectRatioAdjust = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public static int latLngBoundsNorthEastLatitude = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public static int latLngBoundsNorthEastLongitude = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public static int latLngBoundsSouthWestLatitude = 2130771999;
			
			// aapt resource value: 0x7F010020
			public static int latLngBoundsSouthWestLongitude = 2130772000;
			
			// aapt resource value: 0x7F010021
			public static int liteMode = 2130772001;
			
			// aapt resource value: 0x7F010022
			public static int mapType = 2130772002;
			
			// aapt resource value: 0x7F010000
			public static int MvxBind = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int MvxDropDownItemTemplate = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int MvxGroupItemTemplate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int MvxLang = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int MvxSource = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int MvxTemplate = 2130771974;
			
			// aapt resource value: 0x7F010023
			public static int scopeUris = 2130772003;
			
			// aapt resource value: 0x7F010024
			public static int uiCompass = 2130772004;
			
			// aapt resource value: 0x7F010025
			public static int uiMapToolbar = 2130772005;
			
			// aapt resource value: 0x7F010026
			public static int uiRotateGestures = 2130772006;
			
			// aapt resource value: 0x7F010027
			public static int uiScrollGestures = 2130772007;
			
			// aapt resource value: 0x7F010028
			public static int uiTiltGestures = 2130772008;
			
			// aapt resource value: 0x7F010029
			public static int uiZoomControls = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public static int uiZoomGestures = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public static int useViewLifecycle = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public static int zOrderOnTop = 2130772012;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public static int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public static int common_google_signin_btn_text_dark = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int common_google_signin_btn_text_dark_default = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int common_google_signin_btn_text_dark_disabled = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int common_google_signin_btn_text_dark_focused = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int common_google_signin_btn_text_dark_pressed = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int common_google_signin_btn_text_light = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int common_google_signin_btn_text_light_default = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int common_google_signin_btn_text_light_disabled = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int common_google_signin_btn_text_light_focused = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int common_google_signin_btn_text_light_pressed = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int common_google_signin_btn_tint = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public static int notification_action_color_filter = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public static int notification_icon_bg_color = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public static int notification_material_background_media_default_color = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public static int primary_text_default_material_dark = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public static int ripple_material_light = 2130903055;
			
			// aapt resource value: 0x7F030010
			public static int secondary_text_default_material_dark = 2130903056;
			
			// aapt resource value: 0x7F030011
			public static int secondary_text_default_material_light = 2130903057;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public static int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int notification_action_icon_size = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int notification_action_text_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int notification_big_circle_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int notification_content_margin_start = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int notification_large_icon_height = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int notification_large_icon_width = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int notification_right_icon_size = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int notification_right_side_padding_top = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public static int notification_small_icon_background_padding = 2130968591;
			
			// aapt resource value: 0x7F040010
			public static int notification_small_icon_size_as_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public static int notification_subtext_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public static int notification_top_pad = 2130968594;
			
			// aapt resource value: 0x7F040013
			public static int notification_top_pad_large_text = 2130968595;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public static int common_full_open_on_phone = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int common_google_signin_btn_icon_dark = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int common_google_signin_btn_icon_dark_focused = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int common_google_signin_btn_icon_dark_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int common_google_signin_btn_icon_dark_normal_background = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int common_google_signin_btn_icon_disabled = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int common_google_signin_btn_icon_light = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int common_google_signin_btn_icon_light_focused = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int common_google_signin_btn_icon_light_normal = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int common_google_signin_btn_icon_light_normal_background = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int common_google_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int common_google_signin_btn_text_dark_focused = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public static int common_google_signin_btn_text_dark_normal = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public static int common_google_signin_btn_text_dark_normal_background = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public static int common_google_signin_btn_text_disabled = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public static int common_google_signin_btn_text_light = 2131034127;
			
			// aapt resource value: 0x7F050010
			public static int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7F050011
			public static int common_google_signin_btn_text_light_normal = 2131034129;
			
			// aapt resource value: 0x7F050012
			public static int common_google_signin_btn_text_light_normal_background = 2131034130;
			
			// aapt resource value: 0x7F050013
			public static int googleg_disabled_color_18 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public static int googleg_standard_color_18 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public static int notification_action_background = 2131034133;
			
			// aapt resource value: 0x7F050016
			public static int notification_bg = 2131034134;
			
			// aapt resource value: 0x7F050017
			public static int notification_bg_low = 2131034135;
			
			// aapt resource value: 0x7F050018
			public static int notification_bg_low_normal = 2131034136;
			
			// aapt resource value: 0x7F050019
			public static int notification_bg_low_pressed = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public static int notification_bg_normal = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public static int notification_bg_normal_pressed = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public static int notification_icon_background = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public static int notification_template_icon_bg = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public static int notification_template_icon_low_bg = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public static int notification_tile_bg = 2131034143;
			
			// aapt resource value: 0x7F050020
			public static int notify_panel_notification_icon_bg = 2131034144;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060002
			public static int action0 = 2131099650;
			
			// aapt resource value: 0x7F060007
			public static int actions = 2131099655;
			
			// aapt resource value: 0x7F060003
			public static int action_container = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int action_divider = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int action_image = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int action_text = 2131099654;
			
			// aapt resource value: 0x7F060008
			public static int adjust_height = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int adjust_width = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int async = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int auto = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int blocking = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public static int cancel_action = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public static int chronometer = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public static int dark = 2131099663;
			
			// aapt resource value: 0x7F060010
			public static int end_padder = 2131099664;
			
			// aapt resource value: 0x7F060011
			public static int forever = 2131099665;
			
			// aapt resource value: 0x7F060012
			public static int hybrid = 2131099666;
			
			// aapt resource value: 0x7F060013
			public static int icon = 2131099667;
			
			// aapt resource value: 0x7F060014
			public static int icon_group = 2131099668;
			
			// aapt resource value: 0x7F060015
			public static int icon_only = 2131099669;
			
			// aapt resource value: 0x7F060016
			public static int info = 2131099670;
			
			// aapt resource value: 0x7F060017
			public static int italic = 2131099671;
			
			// aapt resource value: 0x7F060018
			public static int light = 2131099672;
			
			// aapt resource value: 0x7F060019
			public static int line1 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public static int line3 = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public static int media_actions = 2131099675;
			
			// aapt resource value: 0x7F060000
			public static int MvvmCrossTagId = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int MvxBindingTagUnique = 2131099649;
			
			// aapt resource value: 0x7F06001C
			public static int none = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public static int normal = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public static int notification_background = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public static int notification_main_column = 2131099679;
			
			// aapt resource value: 0x7F060020
			public static int notification_main_column_container = 2131099680;
			
			// aapt resource value: 0x7F060021
			public static int right_icon = 2131099681;
			
			// aapt resource value: 0x7F060022
			public static int right_side = 2131099682;
			
			// aapt resource value: 0x7F060023
			public static int satellite = 2131099683;
			
			// aapt resource value: 0x7F060024
			public static int standard = 2131099684;
			
			// aapt resource value: 0x7F060025
			public static int status_bar_latest_event_content = 2131099685;
			
			// aapt resource value: 0x7F060026
			public static int tag_transition_group = 2131099686;
			
			// aapt resource value: 0x7F060027
			public static int terrain = 2131099687;
			
			// aapt resource value: 0x7F060028
			public static int text = 2131099688;
			
			// aapt resource value: 0x7F060029
			public static int text2 = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public static int time = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public static int title = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public static int wide = 2131099692;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public static int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int google_play_services_version = 2131165185;
			
			// aapt resource value: 0x7F070002
			public static int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public static int notification_action = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int notification_action_tombstone = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int notification_media_action = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int notification_media_cancel_action = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int notification_template_big_media = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int notification_template_big_media_custom = 2131230725;
			
			// aapt resource value: 0x7F080006
			public static int notification_template_big_media_narrow = 2131230726;
			
			// aapt resource value: 0x7F080007
			public static int notification_template_big_media_narrow_custom = 2131230727;
			
			// aapt resource value: 0x7F080008
			public static int notification_template_custom_big = 2131230728;
			
			// aapt resource value: 0x7F080009
			public static int notification_template_icon_group = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public static int notification_template_lines_media = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public static int notification_template_media = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public static int notification_template_media_custom = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public static int notification_template_part_chronometer = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public static int notification_template_part_time = 2131230734;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public static int common_google_play_services_enable_button = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int common_google_play_services_enable_text = 2131296257;
			
			// aapt resource value: 0x7F090002
			public static int common_google_play_services_enable_title = 2131296258;
			
			// aapt resource value: 0x7F090003
			public static int common_google_play_services_install_button = 2131296259;
			
			// aapt resource value: 0x7F090004
			public static int common_google_play_services_install_text = 2131296260;
			
			// aapt resource value: 0x7F090005
			public static int common_google_play_services_install_title = 2131296261;
			
			// aapt resource value: 0x7F090006
			public static int common_google_play_services_notification_ticker = 2131296262;
			
			// aapt resource value: 0x7F090007
			public static int common_google_play_services_unknown_issue = 2131296263;
			
			// aapt resource value: 0x7F090008
			public static int common_google_play_services_unsupported_text = 2131296264;
			
			// aapt resource value: 0x7F090009
			public static int common_google_play_services_update_button = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public static int common_google_play_services_update_text = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public static int common_google_play_services_update_title = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public static int common_google_play_services_updating_text = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public static int common_google_play_services_wear_update_text = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public static int common_open_on_phone = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public static int common_signin_button_text = 2131296271;
			
			// aapt resource value: 0x7F090010
			public static int common_signin_button_text_long = 2131296272;
			
			// aapt resource value: 0x7F090011
			public static int library_name = 2131296273;
			
			// aapt resource value: 0x7F090012
			public static int status_bar_notification_info_overflow = 2131296274;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public static int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public static int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public static int TextAppearance_Compat_Notification_Info_Media = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public static int TextAppearance_Compat_Notification_Line2 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public static int TextAppearance_Compat_Notification_Media = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public static int TextAppearance_Compat_Notification_Time = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public static int TextAppearance_Compat_Notification_Time_Media = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public static int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public static int TextAppearance_Compat_Notification_Title_Media = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public static int Widget_Compat_NotificationActionContainer = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public static int Widget_Compat_NotificationActionText = 2131361803;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010018 }
			public static int[] FontFamily = new int[] {
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x7F010012,0x7F010019,0x7F01001A }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771986,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public static int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public static int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public static int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x7F010010,0x7F01001B,0x7F01001C }
			public static int[] LoadingImageView = new int[] {
					2130771984,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public static int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public static int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010007,0x7F010009,0x7F01000A,0x7F01000B,0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C }
			public static int[] MapAttrs = new int[] {
					2130771975,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012};
			
			// aapt resource value: 0
			public static int MapAttrs_ambientEnabled = 0;
			
			// aapt resource value: 1
			public static int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public static int MapAttrs_cameraMaxZoomPreference = 2;
			
			// aapt resource value: 3
			public static int MapAttrs_cameraMinZoomPreference = 3;
			
			// aapt resource value: 4
			public static int MapAttrs_cameraTargetLat = 4;
			
			// aapt resource value: 5
			public static int MapAttrs_cameraTargetLng = 5;
			
			// aapt resource value: 6
			public static int MapAttrs_cameraTilt = 6;
			
			// aapt resource value: 7
			public static int MapAttrs_cameraZoom = 7;
			
			// aapt resource value: 8
			public static int MapAttrs_latLngBoundsNorthEastLatitude = 8;
			
			// aapt resource value: 9
			public static int MapAttrs_latLngBoundsNorthEastLongitude = 9;
			
			// aapt resource value: 10
			public static int MapAttrs_latLngBoundsSouthWestLatitude = 10;
			
			// aapt resource value: 11
			public static int MapAttrs_latLngBoundsSouthWestLongitude = 11;
			
			// aapt resource value: 12
			public static int MapAttrs_liteMode = 12;
			
			// aapt resource value: 13
			public static int MapAttrs_mapType = 13;
			
			// aapt resource value: 14
			public static int MapAttrs_uiCompass = 14;
			
			// aapt resource value: 15
			public static int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 16
			public static int MapAttrs_uiRotateGestures = 16;
			
			// aapt resource value: 17
			public static int MapAttrs_uiScrollGestures = 17;
			
			// aapt resource value: 18
			public static int MapAttrs_uiTiltGestures = 18;
			
			// aapt resource value: 19
			public static int MapAttrs_uiZoomControls = 19;
			
			// aapt resource value: 20
			public static int MapAttrs_uiZoomGestures = 20;
			
			// aapt resource value: 21
			public static int MapAttrs_useViewLifecycle = 21;
			
			// aapt resource value: 22
			public static int MapAttrs_zOrderOnTop = 22;
			
			// aapt resource value: { 0x7F010000,0x7F010004 }
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771972};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F010006 }
			public static int[] MvxControl = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010002 }
			public static int[] MvxExpandableListView = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010005 }
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010003 }
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771971};
			
			// aapt resource value: 0
			public static int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public static int MvxListView_MvxItemTemplate = 1;
			
			// aapt resource value: { 0x7F010008,0x7F010011,0x7F010023 }
			public static int[] SignInButton = new int[] {
					2130771976,
					2130771985,
					2130772003};
			
			// aapt resource value: 0
			public static int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public static int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public static int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
