#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppRopio.ECommerce.Marked.Droid.Resource", IsApplication=false)]

namespace AppRopio.ECommerce.Marked.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public static int app_marked_ic_empty_image = 2130771968;
			
			// aapt resource value: 0x7F010001
			public static int barrierAllowsGoneWidgets = 2130771969;
			
			// aapt resource value: 0x7F010002
			public static int barrierDirection = 2130771970;
			
			// aapt resource value: 0x7F010003
			public static int cardBackgroundColor = 2130771971;
			
			// aapt resource value: 0x7F010004
			public static int cardCornerRadius = 2130771972;
			
			// aapt resource value: 0x7F010005
			public static int cardElevation = 2130771973;
			
			// aapt resource value: 0x7F010006
			public static int cardMaxElevation = 2130771974;
			
			// aapt resource value: 0x7F010007
			public static int cardPreventCornerOverlap = 2130771975;
			
			// aapt resource value: 0x7F010008
			public static int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7F010009
			public static int chainUseRtl = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public static int constraintSet = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public static int constraint_referenced_ids = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public static int content = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public static int contentPadding = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public static int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public static int contentPaddingLeft = 2130771983;
			
			// aapt resource value: 0x7F010010
			public static int contentPaddingRight = 2130771984;
			
			// aapt resource value: 0x7F010011
			public static int contentPaddingTop = 2130771985;
			
			// aapt resource value: 0x7F010012
			public static int emptyVisibility = 2130771986;
			
			// aapt resource value: 0x7F010013
			public static int fastScrollEnabled = 2130771987;
			
			// aapt resource value: 0x7F010014
			public static int fastScrollHorizontalThumbDrawable = 2130771988;
			
			// aapt resource value: 0x7F010015
			public static int fastScrollHorizontalTrackDrawable = 2130771989;
			
			// aapt resource value: 0x7F010016
			public static int fastScrollVerticalThumbDrawable = 2130771990;
			
			// aapt resource value: 0x7F010017
			public static int fastScrollVerticalTrackDrawable = 2130771991;
			
			// aapt resource value: 0x7F010018
			public static int font = 2130771992;
			
			// aapt resource value: 0x7F010019
			public static int fontProviderAuthority = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public static int fontProviderCerts = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public static int fontProviderFetchStrategy = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public static int fontProviderFetchTimeout = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public static int fontProviderPackage = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public static int fontProviderQuery = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public static int fontStyle = 2130771999;
			
			// aapt resource value: 0x7F010020
			public static int fontWeight = 2130772000;
			
			// aapt resource value: 0x7F010021
			public static int layoutManager = 2130772001;
			
			// aapt resource value: 0x7F010022
			public static int layout_constrainedHeight = 2130772002;
			
			// aapt resource value: 0x7F010023
			public static int layout_constrainedWidth = 2130772003;
			
			// aapt resource value: 0x7F010024
			public static int layout_constraintBaseline_creator = 2130772004;
			
			// aapt resource value: 0x7F010025
			public static int layout_constraintBaseline_toBaselineOf = 2130772005;
			
			// aapt resource value: 0x7F010026
			public static int layout_constraintBottom_creator = 2130772006;
			
			// aapt resource value: 0x7F010027
			public static int layout_constraintBottom_toBottomOf = 2130772007;
			
			// aapt resource value: 0x7F010028
			public static int layout_constraintBottom_toTopOf = 2130772008;
			
			// aapt resource value: 0x7F010029
			public static int layout_constraintCircle = 2130772009;
			
			// aapt resource value: 0x7F01002A
			public static int layout_constraintCircleAngle = 2130772010;
			
			// aapt resource value: 0x7F01002B
			public static int layout_constraintCircleRadius = 2130772011;
			
			// aapt resource value: 0x7F01002C
			public static int layout_constraintDimensionRatio = 2130772012;
			
			// aapt resource value: 0x7F01002D
			public static int layout_constraintEnd_toEndOf = 2130772013;
			
			// aapt resource value: 0x7F01002E
			public static int layout_constraintEnd_toStartOf = 2130772014;
			
			// aapt resource value: 0x7F01002F
			public static int layout_constraintGuide_begin = 2130772015;
			
			// aapt resource value: 0x7F010030
			public static int layout_constraintGuide_end = 2130772016;
			
			// aapt resource value: 0x7F010031
			public static int layout_constraintGuide_percent = 2130772017;
			
			// aapt resource value: 0x7F010032
			public static int layout_constraintHeight_default = 2130772018;
			
			// aapt resource value: 0x7F010033
			public static int layout_constraintHeight_max = 2130772019;
			
			// aapt resource value: 0x7F010034
			public static int layout_constraintHeight_min = 2130772020;
			
			// aapt resource value: 0x7F010035
			public static int layout_constraintHeight_percent = 2130772021;
			
			// aapt resource value: 0x7F010036
			public static int layout_constraintHorizontal_bias = 2130772022;
			
			// aapt resource value: 0x7F010037
			public static int layout_constraintHorizontal_chainStyle = 2130772023;
			
			// aapt resource value: 0x7F010038
			public static int layout_constraintHorizontal_weight = 2130772024;
			
			// aapt resource value: 0x7F010039
			public static int layout_constraintLeft_creator = 2130772025;
			
			// aapt resource value: 0x7F01003A
			public static int layout_constraintLeft_toLeftOf = 2130772026;
			
			// aapt resource value: 0x7F01003B
			public static int layout_constraintLeft_toRightOf = 2130772027;
			
			// aapt resource value: 0x7F01003C
			public static int layout_constraintRight_creator = 2130772028;
			
			// aapt resource value: 0x7F01003D
			public static int layout_constraintRight_toLeftOf = 2130772029;
			
			// aapt resource value: 0x7F01003E
			public static int layout_constraintRight_toRightOf = 2130772030;
			
			// aapt resource value: 0x7F01003F
			public static int layout_constraintStart_toEndOf = 2130772031;
			
			// aapt resource value: 0x7F010040
			public static int layout_constraintStart_toStartOf = 2130772032;
			
			// aapt resource value: 0x7F010041
			public static int layout_constraintTop_creator = 2130772033;
			
			// aapt resource value: 0x7F010042
			public static int layout_constraintTop_toBottomOf = 2130772034;
			
			// aapt resource value: 0x7F010043
			public static int layout_constraintTop_toTopOf = 2130772035;
			
			// aapt resource value: 0x7F010044
			public static int layout_constraintVertical_bias = 2130772036;
			
			// aapt resource value: 0x7F010045
			public static int layout_constraintVertical_chainStyle = 2130772037;
			
			// aapt resource value: 0x7F010046
			public static int layout_constraintVertical_weight = 2130772038;
			
			// aapt resource value: 0x7F010047
			public static int layout_constraintWidth_default = 2130772039;
			
			// aapt resource value: 0x7F010048
			public static int layout_constraintWidth_max = 2130772040;
			
			// aapt resource value: 0x7F010049
			public static int layout_constraintWidth_min = 2130772041;
			
			// aapt resource value: 0x7F01004A
			public static int layout_constraintWidth_percent = 2130772042;
			
			// aapt resource value: 0x7F01004B
			public static int layout_editor_absoluteX = 2130772043;
			
			// aapt resource value: 0x7F01004C
			public static int layout_editor_absoluteY = 2130772044;
			
			// aapt resource value: 0x7F01004D
			public static int layout_goneMarginBottom = 2130772045;
			
			// aapt resource value: 0x7F01004E
			public static int layout_goneMarginEnd = 2130772046;
			
			// aapt resource value: 0x7F01004F
			public static int layout_goneMarginLeft = 2130772047;
			
			// aapt resource value: 0x7F010050
			public static int layout_goneMarginRight = 2130772048;
			
			// aapt resource value: 0x7F010051
			public static int layout_goneMarginStart = 2130772049;
			
			// aapt resource value: 0x7F010052
			public static int layout_goneMarginTop = 2130772050;
			
			// aapt resource value: 0x7F010053
			public static int layout_optimizationLevel = 2130772051;
			
			// aapt resource value: 0x7F010054
			public static int MvxBind = 2130772052;
			
			// aapt resource value: 0x7F010055
			public static int MvxDropDownItemTemplate = 2130772053;
			
			// aapt resource value: 0x7F010056
			public static int MvxGroupItemTemplate = 2130772054;
			
			// aapt resource value: 0x7F010057
			public static int MvxItemTemplate = 2130772055;
			
			// aapt resource value: 0x7F010058
			public static int MvxLang = 2130772056;
			
			// aapt resource value: 0x7F010059
			public static int MvxSource = 2130772057;
			
			// aapt resource value: 0x7F01005A
			public static int MvxTemplate = 2130772058;
			
			// aapt resource value: 0x7F01005B
			public static int MvxTemplateSelector = 2130772059;
			
			// aapt resource value: 0x7F01005C
			public static int reverseLayout = 2130772060;
			
			// aapt resource value: 0x7F01005D
			public static int spanCount = 2130772061;
			
			// aapt resource value: 0x7F01005E
			public static int stackFromEnd = 2130772062;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public static int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public static int cardview_dark_background = 2130903040;
			
			// aapt resource value: 0x7F030001
			public static int cardview_light_background = 2130903041;
			
			// aapt resource value: 0x7F030002
			public static int cardview_shadow_end_color = 2130903042;
			
			// aapt resource value: 0x7F030003
			public static int cardview_shadow_start_color = 2130903043;
			
			// aapt resource value: 0x7F030004
			public static int notification_action_color_filter = 2130903044;
			
			// aapt resource value: 0x7F030005
			public static int notification_icon_bg_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public static int notification_material_background_media_default_color = 2130903046;
			
			// aapt resource value: 0x7F030007
			public static int primary_text_default_material_dark = 2130903047;
			
			// aapt resource value: 0x7F030008
			public static int ripple_material_light = 2130903048;
			
			// aapt resource value: 0x7F030009
			public static int secondary_text_default_material_dark = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public static int secondary_text_default_material_light = 2130903050;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public static int cardview_compat_inset_shadow = 2130968576;
			
			// aapt resource value: 0x7F040001
			public static int cardview_default_elevation = 2130968577;
			
			// aapt resource value: 0x7F040002
			public static int cardview_default_radius = 2130968578;
			
			// aapt resource value: 0x7F040003
			public static int compat_button_inset_horizontal_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public static int compat_button_inset_vertical_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public static int compat_button_padding_horizontal_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public static int compat_button_padding_vertical_material = 2130968582;
			
			// aapt resource value: 0x7F040007
			public static int compat_control_corner_material = 2130968583;
			
			// aapt resource value: 0x7F040008
			public static int fastscroll_default_thickness = 2130968584;
			
			// aapt resource value: 0x7F040009
			public static int fastscroll_margin = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public static int fastscroll_minimum_range = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public static int item_touch_helper_max_drag_scroll_per_frame = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public static int item_touch_helper_swipe_escape_max_velocity = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public static int item_touch_helper_swipe_escape_velocity = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public static int notification_action_icon_size = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public static int notification_action_text_size = 2130968591;
			
			// aapt resource value: 0x7F040010
			public static int notification_big_circle_margin = 2130968592;
			
			// aapt resource value: 0x7F040011
			public static int notification_content_margin_start = 2130968593;
			
			// aapt resource value: 0x7F040012
			public static int notification_large_icon_height = 2130968594;
			
			// aapt resource value: 0x7F040013
			public static int notification_large_icon_width = 2130968595;
			
			// aapt resource value: 0x7F040014
			public static int notification_main_column_padding_top = 2130968596;
			
			// aapt resource value: 0x7F040015
			public static int notification_media_narrow_margin = 2130968597;
			
			// aapt resource value: 0x7F040016
			public static int notification_right_icon_size = 2130968598;
			
			// aapt resource value: 0x7F040017
			public static int notification_right_side_padding_top = 2130968599;
			
			// aapt resource value: 0x7F040018
			public static int notification_small_icon_background_padding = 2130968600;
			
			// aapt resource value: 0x7F040019
			public static int notification_small_icon_size_as_large = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public static int notification_subtext_size = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public static int notification_top_pad = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public static int notification_top_pad_large_text = 2130968604;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public static int notification_action_background = 2131034112;
			
			// aapt resource value: 0x7F050001
			public static int notification_bg = 2131034113;
			
			// aapt resource value: 0x7F050002
			public static int notification_bg_low = 2131034114;
			
			// aapt resource value: 0x7F050003
			public static int notification_bg_low_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public static int notification_bg_low_pressed = 2131034116;
			
			// aapt resource value: 0x7F050005
			public static int notification_bg_normal = 2131034117;
			
			// aapt resource value: 0x7F050006
			public static int notification_bg_normal_pressed = 2131034118;
			
			// aapt resource value: 0x7F050007
			public static int notification_icon_background = 2131034119;
			
			// aapt resource value: 0x7F050008
			public static int notification_template_icon_bg = 2131034120;
			
			// aapt resource value: 0x7F050009
			public static int notification_template_icon_low_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public static int notification_tile_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public static int notify_panel_notification_icon_bg = 2131034123;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public static int action0 = 2131099648;
			
			// aapt resource value: 0x7F060001
			public static int actions = 2131099649;
			
			// aapt resource value: 0x7F060002
			public static int action_container = 2131099650;
			
			// aapt resource value: 0x7F060003
			public static int action_divider = 2131099651;
			
			// aapt resource value: 0x7F060004
			public static int action_image = 2131099652;
			
			// aapt resource value: 0x7F060005
			public static int action_text = 2131099653;
			
			// aapt resource value: 0x7F060006
			public static int app_marked_empty_button = 2131099654;
			
			// aapt resource value: 0x7F060007
			public static int app_marked_items = 2131099655;
			
			// aapt resource value: 0x7F060008
			public static int async = 2131099656;
			
			// aapt resource value: 0x7F060009
			public static int barrier = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public static int blocking = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public static int bottom = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public static int cancel_action = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public static int chains = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public static int chronometer = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public static int dimensions = 2131099663;
			
			// aapt resource value: 0x7F060010
			public static int direct = 2131099664;
			
			// aapt resource value: 0x7F060011
			public static int end = 2131099665;
			
			// aapt resource value: 0x7F060012
			public static int end_padder = 2131099666;
			
			// aapt resource value: 0x7F060013
			public static int forever = 2131099667;
			
			// aapt resource value: 0x7F060014
			public static int gone = 2131099668;
			
			// aapt resource value: 0x7F060015
			public static int icon = 2131099669;
			
			// aapt resource value: 0x7F060016
			public static int icon_group = 2131099670;
			
			// aapt resource value: 0x7F060017
			public static int info = 2131099671;
			
			// aapt resource value: 0x7F060018
			public static int invisible = 2131099672;
			
			// aapt resource value: 0x7F060019
			public static int italic = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public static int item_touch_helper_previous_elevation = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public static int left = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public static int line1 = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public static int line3 = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public static int media_actions = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public static int MvvmCrossTagId = 2131099679;
			
			// aapt resource value: 0x7F060020
			public static int MvxBindingTagUnique = 2131099680;
			
			// aapt resource value: 0x7F060021
			public static int none = 2131099681;
			
			// aapt resource value: 0x7F060022
			public static int normal = 2131099682;
			
			// aapt resource value: 0x7F060023
			public static int notification_background = 2131099683;
			
			// aapt resource value: 0x7F060024
			public static int notification_main_column = 2131099684;
			
			// aapt resource value: 0x7F060025
			public static int notification_main_column_container = 2131099685;
			
			// aapt resource value: 0x7F060026
			public static int packed = 2131099686;
			
			// aapt resource value: 0x7F060027
			public static int parent = 2131099687;
			
			// aapt resource value: 0x7F060028
			public static int percent = 2131099688;
			
			// aapt resource value: 0x7F060029
			public static int right = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public static int right_icon = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public static int right_side = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public static int spread = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public static int spread_inside = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public static int standard = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public static int start = 2131099695;
			
			// aapt resource value: 0x7F060030
			public static int status_bar_latest_event_content = 2131099696;
			
			// aapt resource value: 0x7F060031
			public static int tag_transition_group = 2131099697;
			
			// aapt resource value: 0x7F060032
			public static int text = 2131099698;
			
			// aapt resource value: 0x7F060033
			public static int text2 = 2131099699;
			
			// aapt resource value: 0x7F060034
			public static int time = 2131099700;
			
			// aapt resource value: 0x7F060035
			public static int title = 2131099701;
			
			// aapt resource value: 0x7F060036
			public static int top = 2131099702;
			
			// aapt resource value: 0x7F060037
			public static int wrap = 2131099703;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public static int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public static int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public static int app_marked = 2131230720;
			
			// aapt resource value: 0x7F080001
			public static int app_marked_empty = 2131230721;
			
			// aapt resource value: 0x7F080002
			public static int notification_action = 2131230722;
			
			// aapt resource value: 0x7F080003
			public static int notification_action_tombstone = 2131230723;
			
			// aapt resource value: 0x7F080004
			public static int notification_media_action = 2131230724;
			
			// aapt resource value: 0x7F080005
			public static int notification_media_cancel_action = 2131230725;
			
			// aapt resource value: 0x7F080006
			public static int notification_template_big_media = 2131230726;
			
			// aapt resource value: 0x7F080007
			public static int notification_template_big_media_custom = 2131230727;
			
			// aapt resource value: 0x7F080008
			public static int notification_template_big_media_narrow = 2131230728;
			
			// aapt resource value: 0x7F080009
			public static int notification_template_big_media_narrow_custom = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public static int notification_template_custom_big = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public static int notification_template_icon_group = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public static int notification_template_lines_media = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public static int notification_template_media = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public static int notification_template_media_custom = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public static int notification_template_part_chronometer = 2131230735;
			
			// aapt resource value: 0x7F080010
			public static int notification_template_part_time = 2131230736;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public static int library_name = 2131296256;
			
			// aapt resource value: 0x7F090001
			public static int status_bar_notification_info_overflow = 2131296257;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public static int app_marked_empty_button = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public static int app_marked_empty_subtitle = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public static int app_marked_empty_title = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public static int app_marked_items = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public static int Base_CardView = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public static int CardView = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public static int CardView_Dark = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public static int CardView_Light = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public static int TextAppearance_Compat_Notification = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public static int TextAppearance_Compat_Notification_Info = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public static int TextAppearance_Compat_Notification_Info_Media = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public static int TextAppearance_Compat_Notification_Line2 = 2131361803;
			
			// aapt resource value: 0x7F0A000C
			public static int TextAppearance_Compat_Notification_Line2_Media = 2131361804;
			
			// aapt resource value: 0x7F0A000D
			public static int TextAppearance_Compat_Notification_Media = 2131361805;
			
			// aapt resource value: 0x7F0A000E
			public static int TextAppearance_Compat_Notification_Time = 2131361806;
			
			// aapt resource value: 0x7F0A000F
			public static int TextAppearance_Compat_Notification_Time_Media = 2131361807;
			
			// aapt resource value: 0x7F0A0010
			public static int TextAppearance_Compat_Notification_Title = 2131361808;
			
			// aapt resource value: 0x7F0A0011
			public static int TextAppearance_Compat_Notification_Title_Media = 2131361809;
			
			// aapt resource value: 0x7F0A0012
			public static int Widget_Compat_NotificationActionContainer = 2131361810;
			
			// aapt resource value: 0x7F0A0013
			public static int Widget_Compat_NotificationActionText = 2131361811;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x1010140,0x101013F,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011 }
			public static int[] CardView = new int[] {
					16843072,
					16843071,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public static int CardView_android_minHeight = 0;
			
			// aapt resource value: 1
			public static int CardView_android_minWidth = 1;
			
			// aapt resource value: 2
			public static int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public static int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public static int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public static int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 6
			public static int CardView_cardPreventCornerOverlap = 6;
			
			// aapt resource value: 7
			public static int CardView_cardUseCompatPadding = 7;
			
			// aapt resource value: 8
			public static int CardView_contentPadding = 8;
			
			// aapt resource value: 9
			public static int CardView_contentPaddingBottom = 9;
			
			// aapt resource value: 10
			public static int CardView_contentPaddingLeft = 10;
			
			// aapt resource value: 11
			public static int CardView_contentPaddingRight = 11;
			
			// aapt resource value: 12
			public static int CardView_contentPaddingTop = 12;
			
			// aapt resource value: { 0x1010120,0x101011F,0x1010140,0x101013F,0x10100C4,0x7F010001,0x7F010002,0x7F010009,0x7F01000A,0x7F01000B,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C,0x7F01002D,0x7F01002E,0x7F01002F,0x7F010030,0x7F010031,0x7F010032,0x7F010033,0x7F010034,0x7F010035,0x7F010036,0x7F010037,0x7F010038,0x7F010039,0x7F01003A,0x7F01003B,0x7F01003C,0x7F01003D,0x7F01003E,0x7F01003F,0x7F010040,0x7F010041,0x7F010042,0x7F010043,0x7F010044,0x7F010045,0x7F010046,0x7F010047,0x7F010048,0x7F010049,0x7F01004A,0x7F01004B,0x7F01004C,0x7F01004D,0x7F01004E,0x7F01004F,0x7F010050,0x7F010051,0x7F010052,0x7F010053 }
			public static int[] ConstraintLayout_Layout = new int[] {
					16843040,
					16843039,
					16843072,
					16843071,
					16842948,
					2130771969,
					2130771970,
					2130771977,
					2130771978,
					2130771979,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051};
			
			// aapt resource value: 0
			public static int ConstraintLayout_Layout_android_maxHeight = 0;
			
			// aapt resource value: 1
			public static int ConstraintLayout_Layout_android_maxWidth = 1;
			
			// aapt resource value: 2
			public static int ConstraintLayout_Layout_android_minHeight = 2;
			
			// aapt resource value: 3
			public static int ConstraintLayout_Layout_android_minWidth = 3;
			
			// aapt resource value: 4
			public static int ConstraintLayout_Layout_android_orientation = 4;
			
			// aapt resource value: 5
			public static int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
			
			// aapt resource value: 6
			public static int ConstraintLayout_Layout_barrierDirection = 6;
			
			// aapt resource value: 7
			public static int ConstraintLayout_Layout_chainUseRtl = 7;
			
			// aapt resource value: 8
			public static int ConstraintLayout_Layout_constraintSet = 8;
			
			// aapt resource value: 9
			public static int ConstraintLayout_Layout_constraint_referenced_ids = 9;
			
			// aapt resource value: 10
			public static int ConstraintLayout_Layout_layout_constrainedHeight = 10;
			
			// aapt resource value: 11
			public static int ConstraintLayout_Layout_layout_constrainedWidth = 11;
			
			// aapt resource value: 12
			public static int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
			
			// aapt resource value: 13
			public static int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
			
			// aapt resource value: 14
			public static int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
			
			// aapt resource value: 15
			public static int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
			
			// aapt resource value: 16
			public static int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
			
			// aapt resource value: 17
			public static int ConstraintLayout_Layout_layout_constraintCircle = 17;
			
			// aapt resource value: 18
			public static int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
			
			// aapt resource value: 19
			public static int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
			
			// aapt resource value: 20
			public static int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
			
			// aapt resource value: 21
			public static int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
			
			// aapt resource value: 22
			public static int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
			
			// aapt resource value: 23
			public static int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
			
			// aapt resource value: 24
			public static int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
			
			// aapt resource value: 25
			public static int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
			
			// aapt resource value: 26
			public static int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
			
			// aapt resource value: 27
			public static int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
			
			// aapt resource value: 28
			public static int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
			
			// aapt resource value: 29
			public static int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
			
			// aapt resource value: 30
			public static int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
			
			// aapt resource value: 31
			public static int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
			
			// aapt resource value: 32
			public static int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
			
			// aapt resource value: 33
			public static int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
			
			// aapt resource value: 34
			public static int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
			
			// aapt resource value: 35
			public static int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
			
			// aapt resource value: 36
			public static int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
			
			// aapt resource value: 37
			public static int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
			
			// aapt resource value: 38
			public static int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
			
			// aapt resource value: 39
			public static int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
			
			// aapt resource value: 40
			public static int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
			
			// aapt resource value: 41
			public static int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
			
			// aapt resource value: 42
			public static int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
			
			// aapt resource value: 43
			public static int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
			
			// aapt resource value: 44
			public static int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
			
			// aapt resource value: 45
			public static int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
			
			// aapt resource value: 46
			public static int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
			
			// aapt resource value: 47
			public static int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
			
			// aapt resource value: 48
			public static int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
			
			// aapt resource value: 49
			public static int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
			
			// aapt resource value: 50
			public static int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
			
			// aapt resource value: 51
			public static int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
			
			// aapt resource value: 52
			public static int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
			
			// aapt resource value: 53
			public static int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
			
			// aapt resource value: 54
			public static int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
			
			// aapt resource value: 55
			public static int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
			
			// aapt resource value: 56
			public static int ConstraintLayout_Layout_layout_goneMarginRight = 56;
			
			// aapt resource value: 57
			public static int ConstraintLayout_Layout_layout_goneMarginStart = 57;
			
			// aapt resource value: 58
			public static int ConstraintLayout_Layout_layout_goneMarginTop = 58;
			
			// aapt resource value: 59
			public static int ConstraintLayout_Layout_layout_optimizationLevel = 59;
			
			// aapt resource value: { 0x7F01000C,0x7F010012 }
			public static int[] ConstraintLayout_placeholder = new int[] {
					2130771980,
					2130771986};
			
			// aapt resource value: 0
			public static int ConstraintLayout_placeholder_content = 0;
			
			// aapt resource value: 1
			public static int ConstraintLayout_placeholder_emptyVisibility = 1;
			
			// aapt resource value: { 0x101031F,0x1010440,0x10100D0,0x10100F5,0x10100FA,0x10103B6,0x10100F7,0x10100F9,0x10103B5,0x10100F8,0x10100F4,0x10100C4,0x1010326,0x1010327,0x1010328,0x1010324,0x1010325,0x1010320,0x1010321,0x1010322,0x1010323,0x10103FA,0x10100DC,0x7F010022,0x7F010023,0x7F010024,0x7F010025,0x7F010026,0x7F010027,0x7F010028,0x7F010029,0x7F01002A,0x7F01002B,0x7F01002C,0x7F01002D,0x7F01002E,0x7F01002F,0x7F010030,0x7F010031,0x7F010032,0x7F010033,0x7F010034,0x7F010035,0x7F010036,0x7F010037,0x7F010038,0x7F010039,0x7F01003A,0x7F01003B,0x7F01003C,0x7F01003D,0x7F01003E,0x7F01003F,0x7F010040,0x7F010041,0x7F010042,0x7F010043,0x7F010044,0x7F010045,0x7F010046,0x7F010047,0x7F010048,0x7F010049,0x7F01004A,0x7F01004B,0x7F01004C,0x7F01004D,0x7F01004E,0x7F01004F,0x7F010050,0x7F010051,0x7F010052 }
			public static int[] ConstraintSet = new int[] {
					16843551,
					16843840,
					16842960,
					16842997,
					16843002,
					16843702,
					16842999,
					16843001,
					16843701,
					16843000,
					16842996,
					16842948,
					16843558,
					16843559,
					16843560,
					16843556,
					16843557,
					16843552,
					16843553,
					16843554,
					16843555,
					16843770,
					16842972,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050};
			
			// aapt resource value: 0
			public static int ConstraintSet_android_alpha = 0;
			
			// aapt resource value: 1
			public static int ConstraintSet_android_elevation = 1;
			
			// aapt resource value: 2
			public static int ConstraintSet_android_id = 2;
			
			// aapt resource value: 3
			public static int ConstraintSet_android_layout_height = 3;
			
			// aapt resource value: 4
			public static int ConstraintSet_android_layout_marginBottom = 4;
			
			// aapt resource value: 5
			public static int ConstraintSet_android_layout_marginEnd = 5;
			
			// aapt resource value: 6
			public static int ConstraintSet_android_layout_marginLeft = 6;
			
			// aapt resource value: 7
			public static int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 8
			public static int ConstraintSet_android_layout_marginStart = 8;
			
			// aapt resource value: 9
			public static int ConstraintSet_android_layout_marginTop = 9;
			
			// aapt resource value: 10
			public static int ConstraintSet_android_layout_width = 10;
			
			// aapt resource value: 11
			public static int ConstraintSet_android_orientation = 11;
			
			// aapt resource value: 12
			public static int ConstraintSet_android_rotation = 12;
			
			// aapt resource value: 13
			public static int ConstraintSet_android_rotationX = 13;
			
			// aapt resource value: 14
			public static int ConstraintSet_android_rotationY = 14;
			
			// aapt resource value: 15
			public static int ConstraintSet_android_scaleX = 15;
			
			// aapt resource value: 16
			public static int ConstraintSet_android_scaleY = 16;
			
			// aapt resource value: 17
			public static int ConstraintSet_android_transformPivotX = 17;
			
			// aapt resource value: 18
			public static int ConstraintSet_android_transformPivotY = 18;
			
			// aapt resource value: 19
			public static int ConstraintSet_android_translationX = 19;
			
			// aapt resource value: 20
			public static int ConstraintSet_android_translationY = 20;
			
			// aapt resource value: 21
			public static int ConstraintSet_android_translationZ = 21;
			
			// aapt resource value: 22
			public static int ConstraintSet_android_visibility = 22;
			
			// aapt resource value: 23
			public static int ConstraintSet_layout_constrainedHeight = 23;
			
			// aapt resource value: 24
			public static int ConstraintSet_layout_constrainedWidth = 24;
			
			// aapt resource value: 25
			public static int ConstraintSet_layout_constraintBaseline_creator = 25;
			
			// aapt resource value: 26
			public static int ConstraintSet_layout_constraintBaseline_toBaselineOf = 26;
			
			// aapt resource value: 27
			public static int ConstraintSet_layout_constraintBottom_creator = 27;
			
			// aapt resource value: 28
			public static int ConstraintSet_layout_constraintBottom_toBottomOf = 28;
			
			// aapt resource value: 29
			public static int ConstraintSet_layout_constraintBottom_toTopOf = 29;
			
			// aapt resource value: 30
			public static int ConstraintSet_layout_constraintCircle = 30;
			
			// aapt resource value: 31
			public static int ConstraintSet_layout_constraintCircleAngle = 31;
			
			// aapt resource value: 32
			public static int ConstraintSet_layout_constraintCircleRadius = 32;
			
			// aapt resource value: 33
			public static int ConstraintSet_layout_constraintDimensionRatio = 33;
			
			// aapt resource value: 34
			public static int ConstraintSet_layout_constraintEnd_toEndOf = 34;
			
			// aapt resource value: 35
			public static int ConstraintSet_layout_constraintEnd_toStartOf = 35;
			
			// aapt resource value: 36
			public static int ConstraintSet_layout_constraintGuide_begin = 36;
			
			// aapt resource value: 37
			public static int ConstraintSet_layout_constraintGuide_end = 37;
			
			// aapt resource value: 38
			public static int ConstraintSet_layout_constraintGuide_percent = 38;
			
			// aapt resource value: 39
			public static int ConstraintSet_layout_constraintHeight_default = 39;
			
			// aapt resource value: 40
			public static int ConstraintSet_layout_constraintHeight_max = 40;
			
			// aapt resource value: 41
			public static int ConstraintSet_layout_constraintHeight_min = 41;
			
			// aapt resource value: 42
			public static int ConstraintSet_layout_constraintHeight_percent = 42;
			
			// aapt resource value: 43
			public static int ConstraintSet_layout_constraintHorizontal_bias = 43;
			
			// aapt resource value: 44
			public static int ConstraintSet_layout_constraintHorizontal_chainStyle = 44;
			
			// aapt resource value: 45
			public static int ConstraintSet_layout_constraintHorizontal_weight = 45;
			
			// aapt resource value: 46
			public static int ConstraintSet_layout_constraintLeft_creator = 46;
			
			// aapt resource value: 47
			public static int ConstraintSet_layout_constraintLeft_toLeftOf = 47;
			
			// aapt resource value: 48
			public static int ConstraintSet_layout_constraintLeft_toRightOf = 48;
			
			// aapt resource value: 49
			public static int ConstraintSet_layout_constraintRight_creator = 49;
			
			// aapt resource value: 50
			public static int ConstraintSet_layout_constraintRight_toLeftOf = 50;
			
			// aapt resource value: 51
			public static int ConstraintSet_layout_constraintRight_toRightOf = 51;
			
			// aapt resource value: 52
			public static int ConstraintSet_layout_constraintStart_toEndOf = 52;
			
			// aapt resource value: 53
			public static int ConstraintSet_layout_constraintStart_toStartOf = 53;
			
			// aapt resource value: 54
			public static int ConstraintSet_layout_constraintTop_creator = 54;
			
			// aapt resource value: 55
			public static int ConstraintSet_layout_constraintTop_toBottomOf = 55;
			
			// aapt resource value: 56
			public static int ConstraintSet_layout_constraintTop_toTopOf = 56;
			
			// aapt resource value: 57
			public static int ConstraintSet_layout_constraintVertical_bias = 57;
			
			// aapt resource value: 58
			public static int ConstraintSet_layout_constraintVertical_chainStyle = 58;
			
			// aapt resource value: 59
			public static int ConstraintSet_layout_constraintVertical_weight = 59;
			
			// aapt resource value: 60
			public static int ConstraintSet_layout_constraintWidth_default = 60;
			
			// aapt resource value: 61
			public static int ConstraintSet_layout_constraintWidth_max = 61;
			
			// aapt resource value: 62
			public static int ConstraintSet_layout_constraintWidth_min = 62;
			
			// aapt resource value: 63
			public static int ConstraintSet_layout_constraintWidth_percent = 63;
			
			// aapt resource value: 64
			public static int ConstraintSet_layout_editor_absoluteX = 64;
			
			// aapt resource value: 65
			public static int ConstraintSet_layout_editor_absoluteY = 65;
			
			// aapt resource value: 66
			public static int ConstraintSet_layout_goneMarginBottom = 66;
			
			// aapt resource value: 67
			public static int ConstraintSet_layout_goneMarginEnd = 67;
			
			// aapt resource value: 68
			public static int ConstraintSet_layout_goneMarginLeft = 68;
			
			// aapt resource value: 69
			public static int ConstraintSet_layout_goneMarginRight = 69;
			
			// aapt resource value: 70
			public static int ConstraintSet_layout_goneMarginStart = 70;
			
			// aapt resource value: 71
			public static int ConstraintSet_layout_goneMarginTop = 71;
			
			// aapt resource value: { 0x7F010019,0x7F01001A,0x7F01001B,0x7F01001C,0x7F01001D,0x7F01001E }
			public static int[] FontFamily = new int[] {
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: { 0x1010532,0x101053F,0x1010533,0x7F010018,0x7F01001F,0x7F010020 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844095,
					16844083,
					2130771992,
					2130771999,
					2130772000};
			
			// aapt resource value: 0
			public static int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 1
			public static int FontFamilyFont_android_fontStyle = 1;
			
			// aapt resource value: 2
			public static int FontFamilyFont_android_fontWeight = 2;
			
			// aapt resource value: 3
			public static int FontFamilyFont_font = 3;
			
			// aapt resource value: 4
			public static int FontFamilyFont_fontStyle = 4;
			
			// aapt resource value: 5
			public static int FontFamilyFont_fontWeight = 5;
			
			// aapt resource value: 0
			public static int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public static int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public static int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public static int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public static int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public static int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x10100C4 }
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public static int LinearConstraintLayout_android_orientation = 0;
			
			// aapt resource value: { 0x7F010054,0x7F010058 }
			public static int[] MvxBinding = new int[] {
					2130772052,
					2130772056};
			
			// aapt resource value: 0
			public static int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public static int MvxBinding_MvxLang = 1;
			
			// aapt resource value: { 0x7F01005A }
			public static int[] MvxControl = new int[] {
					2130772058};
			
			// aapt resource value: 0
			public static int MvxControl_MvxTemplate = 0;
			
			// aapt resource value: { 0x7F010056 }
			public static int[] MvxExpandableListView = new int[] {
					2130772054};
			
			// aapt resource value: 0
			public static int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			// aapt resource value: { 0x7F010059 }
			public static int[] MvxImageView = new int[] {
					2130772057};
			
			// aapt resource value: 0
			public static int MvxImageView_MvxSource = 0;
			
			// aapt resource value: { 0x7F010055,0x7F010057 }
			public static int[] MvxListView = new int[] {
					2130772053,
					2130772055};
			
			// aapt resource value: 0
			public static int MvxListView_MvxDropDownItemTemplate = 0;
			
			// aapt resource value: 1
			public static int MvxListView_MvxItemTemplate = 1;
			
			// aapt resource value: { 0x7F01005B }
			public static int[] MvxRecyclerView = new int[] {
					2130772059};
			
			// aapt resource value: 0
			public static int MvxRecyclerView_MvxTemplateSelector = 0;
			
			// aapt resource value: { 0x10100F1,0x10100C4,0x7F010013,0x7F010014,0x7F010015,0x7F010016,0x7F010017,0x7F010021,0x7F01005C,0x7F01005D,0x7F01005E }
			public static int[] RecyclerView = new int[] {
					16842993,
					16842948,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130772001,
					2130772060,
					2130772061,
					2130772062};
			
			// aapt resource value: 0
			public static int RecyclerView_android_descendantFocusability = 0;
			
			// aapt resource value: 1
			public static int RecyclerView_android_orientation = 1;
			
			// aapt resource value: 2
			public static int RecyclerView_fastScrollEnabled = 2;
			
			// aapt resource value: 3
			public static int RecyclerView_fastScrollHorizontalThumbDrawable = 3;
			
			// aapt resource value: 4
			public static int RecyclerView_fastScrollHorizontalTrackDrawable = 4;
			
			// aapt resource value: 5
			public static int RecyclerView_fastScrollVerticalThumbDrawable = 5;
			
			// aapt resource value: 6
			public static int RecyclerView_fastScrollVerticalTrackDrawable = 6;
			
			// aapt resource value: 7
			public static int RecyclerView_layoutManager = 7;
			
			// aapt resource value: 8
			public static int RecyclerView_reverseLayout = 8;
			
			// aapt resource value: 9
			public static int RecyclerView_spanCount = 9;
			
			// aapt resource value: 10
			public static int RecyclerView_stackFromEnd = 10;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
